# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14ec16ed0732fc18fc17fa3f06d2e8add3469f07813092814f992e5331ec42cd7947dd65ef616aab241731ba32edbc4e88204ef59e4f6a8cc1b90c0ae139510a

test:
  secret_key_base: 34d8e01b709ac81fdf6a3097124877249a24da00b6a9f1601894f44e2ed9bac4bbccbc583b5e0ba233f75d5860b2db6c5d7a63895ec14f0016f4727842e3eb30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
